language: python
python:
    - 3.6
notifications:
    email: false
install:
    - "pip install -r requirements.txt"
    - "pip install -r tests/requirements.txt"
jobs:
  include:
    - stage: test
      script: python3 robot/robot.py test
    - stage: format
      script: pycodestyle . --ignore=E501
cache: pip
